export const SET_SUBJECTS_DELETE_IS_LOADING = 'SET_SUBJECTS_DELETE_IS_LOADING';
export const SET_SUBJECTS_DELETE_IS_DELETE = 'SET_SUBJECTS_DELETE_IS_DELETE'
export const SET_SUBJECTS_DELETE_ITEM= 'SET_SUBJECTS_DELETE_ITEM'
export const SET_SUBJECTS_DELETE_MESSAGE = 'SET_SUBJECTS_DELETE_MESSAGE'
export const SET_SUBJECTS_DELETE_RESET = 'SET_SUBJECTS_DELETE_RESET'
