export const SET_BOOKFAVS_CREATE_IS_LOADING = 'SET_BOOKFAVS_CREATE_IS_LOADING';
export const SET_BOOKFAVS_CREATE_IS_CREATE = 'SET_BOOKFAVS_CREATE_IS_CREATE'
export const SET_BOOKFAVS_CREATE_ITEM= 'SET_BOOKFAVS_CREATE_ITEM'
export const SET_BOOKFAVS_CREATE_MESSAGE = 'SET_BOOKFAVS_CREATE_MESSAGE'
export const SET_BOOKFAVS_CREATE_RESET = 'SET_BOOKFAVS_CREATE_RESET'
