export const SET_BOOKFAVS_DELETE_IS_LOADING = 'SET_BOOKFAVS_DELETE_IS_LOADING';
export const SET_BOOKFAVS_DELETE_IS_DELETE = 'SET_BOOKFAVS_DELETE_IS_DELETE'
export const SET_BOOKFAVS_DELETE_ITEM= 'SET_BOOKFAVS_DELETE_ITEM'
export const SET_BOOKFAVS_DELETE_MESSAGE = 'SET_BOOKFAVS_DELETE_MESSAGE'
export const SET_BOOKFAVS_DELETE_RESET = 'SET_BOOKFAVS_DELETE_RESET'
