export const SET_CLASSROOMS_UPDATE_IS_LOADING = 'SET_CLASSROOMS_UPDATE_IS_LOADING';
export const SET_CLASSROOMS_UPDATE_IS_UPDATE = 'SET_CLASSROOMS_UPDATE_IS_UPDATE'
export const SET_CLASSROOMS_UPDATE_ITEM= 'SET_CLASSROOMS_UPDATE_ITEM'
export const SET_CLASSROOMS_UPDATE_MESSAGE = 'SET_CLASSROOMS_UPDATE_MESSAGE'
export const SET_CLASSROOMS_UPDATE_RESET = 'SET_CLASSROOMS_UPDATE_RESET'
