export const SET_REPETITIONS_UPDATE_IS_LOADING = 'SET_REPETITIONS_UPDATE_IS_LOADING';
export const SET_REPETITIONS_UPDATE_IS_UPDATE = 'SET_REPETITIONS_UPDATE_IS_UPDATE'
export const SET_REPETITIONS_UPDATE_ITEM= 'SET_REPETITIONS_UPDATE_ITEM'
export const SET_REPETITIONS_UPDATE_MESSAGE = 'SET_REPETITIONS_UPDATE_MESSAGE'
export const SET_REPETITIONS_UPDATE_RESET = 'SET_REPETITIONS_UPDATE_RESET'
