export const SET_CLASSROOMS_DELETE_IS_LOADING = 'SET_CLASSROOMS_DELETE_IS_LOADING';
export const SET_CLASSROOMS_DELETE_IS_DELETE = 'SET_CLASSROOMS_DELETE_IS_DELETE'
export const SET_CLASSROOMS_DELETE_ITEM= 'SET_CLASSROOMS_DELETE_ITEM'
export const SET_CLASSROOMS_DELETE_MESSAGE = 'SET_CLASSROOMS_DELETE_MESSAGE'
export const SET_CLASSROOMS_DELETE_RESET = 'SET_CLASSROOMS_DELETE_RESET'
