export const SET_USER_REPETS_DELETE_IS_LOADING = 'SET_USER_REPETS_DELETE_IS_LOADING';
export const SET_USER_REPETS_DELETE_IS_DELETE = 'SET_USER_REPETS_DELETE_IS_DELETE'
export const SET_USER_REPETS_DELETE_ITEM= 'SET_USER_REPETS_DELETE_ITEM'
export const SET_USER_REPETS_DELETE_MESSAGE = 'SET_USER_REPETS_DELETE_MESSAGE'
export const SET_USER_REPETS_DELETE_RESET = 'SET_USER_REPETS_DELETE_RESET'
