export const SET_QUIZS_UPDATE_IS_LOADING = 'SET_QUIZS_UPDATE_IS_LOADING';
export const SET_QUIZS_UPDATE_IS_UPDATE = 'SET_QUIZS_UPDATE_IS_UPDATE'
export const SET_QUIZS_UPDATE_ITEM= 'SET_QUIZS_UPDATE_ITEM'
export const SET_QUIZS_UPDATE_MESSAGE = 'SET_QUIZS_UPDATE_MESSAGE'
export const SET_QUIZS_UPDATE_RESET = 'SET_QUIZS_UPDATE_RESET'
