export const SET_USERS_UPDATE_IS_LOADING = 'SET_USERS_UPDATE_IS_LOADING';
export const SET_USERS_UPDATE_IS_UPDATE = 'SET_USERS_UPDATE_IS_UPDATE'
export const SET_USERS_UPDATE_ITEM= 'SET_USERS_UPDATE_ITEM'
export const SET_USERS_UPDATE_MESSAGE = 'SET_USERS_UPDATE_MESSAGE'
export const SET_USERS_UPDATE_RESET = 'SET_USERS_UPDATE_RESET'
