export const SET_REPETITIONS_CREATE_IS_LOADING = 'SET_REPETITIONS_CREATE_IS_LOADING';
export const SET_REPETITIONS_CREATE_IS_CREATE = 'SET_REPETITIONS_CREATE_IS_CREATE'
export const SET_REPETITIONS_CREATE_ITEM= 'SET_REPETITIONS_CREATE_ITEM'
export const SET_REPETITIONS_CREATE_MESSAGE = 'SET_REPETITIONS_CREATE_MESSAGE'
export const SET_REPETITIONS_CREATE_RESET = 'SET_REPETITIONS_CREATE_RESET'
