export const SET_COURS_UPDATE_IS_LOADING = 'SET_COURS_UPDATE_IS_LOADING';
export const SET_COURS_UPDATE_IS_UPDATE = 'SET_COURS_UPDATE_IS_UPDATE'
export const SET_COURS_UPDATE_ITEM= 'SET_COURS_UPDATE_ITEM'
export const SET_COURS_UPDATE_MESSAGE = 'SET_COURS_UPDATE_MESSAGE'
export const SET_COURS_UPDATE_RESET = 'SET_COURS_UPDATE_RESET'
