export const SET_CLASSROOMS_CREATE_IS_LOADING = 'SET_CLASSROOMS_CREATE_IS_LOADING';
export const SET_CLASSROOMS_CREATE_IS_CREATE = 'SET_CLASSROOMS_CREATE_IS_CREATE'
export const SET_CLASSROOMS_CREATE_ITEM= 'SET_CLASSROOMS_CREATE_ITEM'
export const SET_CLASSROOMS_CREATE_MESSAGE = 'SET_CLASSROOMS_CREATE_MESSAGE'
export const SET_CLASSROOMS_CREATE_RESET = 'SET_CLASSROOMS_CREATE_RESET'
