export const SET_EXERCICES_UPDATE_IS_LOADING = 'SET_EXERCICES_UPDATE_IS_LOADING';
export const SET_EXERCICES_UPDATE_IS_UPDATE = 'SET_EXERCICES_UPDATE_IS_UPDATE'
export const SET_EXERCICES_UPDATE_ITEM= 'SET_EXERCICES_UPDATE_ITEM'
export const SET_EXERCICES_UPDATE_MESSAGE = 'SET_EXERCICES_UPDATE_MESSAGE'
export const SET_EXERCICES_UPDATE_RESET = 'SET_EXERCICES_UPDATE_RESET'
