export const SET_QUIZS_CREATE_IS_LOADING = 'SET_QUIZS_CREATE_IS_LOADING';
export const SET_QUIZS_CREATE_IS_CREATE = 'SET_QUIZS_CREATE_IS_CREATE'
export const SET_QUIZS_CREATE_ITEM= 'SET_QUIZS_CREATE_ITEM'
export const SET_QUIZS_CREATE_MESSAGE = 'SET_QUIZS_CREATE_MESSAGE'
export const SET_QUIZS_CREATE_RESET = 'SET_QUIZS_CREATE_RESET'
