export const SET_USER_REPETS_CREATE_IS_LOADING = 'SET_USER_REPETS_CREATE_IS_LOADING';
export const SET_USER_REPETS_CREATE_IS_CREATE = 'SET_USER_REPETS_CREATE_IS_CREATE'
export const SET_USER_REPETS_CREATE_ITEM= 'SET_USER_REPETS_CREATE_ITEM'
export const SET_USER_REPETS_CREATE_MESSAGE = 'SET_USER_REPETS_CREATE_MESSAGE'
export const SET_USER_REPETS_CREATE_RESET = 'SET_USER_REPETS_CREATE_RESET'
