export const SET_SUBJECTS_CREATE_IS_LOADING = 'SET_SUBJECTS_CREATE_IS_LOADING';
export const SET_SUBJECTS_CREATE_IS_CREATE = 'SET_SUBJECTS_CREATE_IS_CREATE'
export const SET_SUBJECTS_CREATE_ITEM= 'SET_SUBJECTS_CREATE_ITEM'
export const SET_SUBJECTS_CREATE_MESSAGE = 'SET_SUBJECTS_CREATE_MESSAGE'
export const SET_SUBJECTS_CREATE_RESET = 'SET_SUBJECTS_CREATE_RESET'
