export const SET_BOOKS_DELETE_IS_LOADING = 'SET_BOOKS_DELETE_IS_LOADING';
export const SET_BOOKS_DELETE_IS_DELETE = 'SET_BOOKS_DELETE_IS_DELETE'
export const SET_BOOKS_DELETE_ITEM= 'SET_BOOKS_DELETE_ITEM'
export const SET_BOOKS_DELETE_MESSAGE = 'SET_BOOKS_DELETE_MESSAGE'
export const SET_BOOKS_DELETE_RESET = 'SET_BOOKS_DELETE_RESET'
