export const SET_BOOKFAVS_LIST_ITEMS = 'SET_BOOKFAVS_LIST_ITEMS';
export const SET_BOOKFAVS_LIST_IS_LOADING = 'SET_BOOKFAVS_LIST_IS_LOADING';
export const SET_BOOKFAVS_LIST_META = 'SET_BOOKFAVS_LIST_META'
export const SET_BOOKFAVS_LIST_LINKS = 'SET_BOOKFAVS_LIST_LINKS'
export const SET_BOOKFAVS_LIST_MESSAGE = 'SET_BOOKFAVS_LIST_MESSAGE'
export const SET_BOOKFAVS_LIST_SEARCH_ITEMS = 'SET_BOOKFAVS_LIST_SEARCH_ITEMS'
export const SET_BOOKFAVS_LIST_RESET = 'SET_BOOKFAVS_LIST_RESET'    