export const SET_REPETITIONS_LIST_ITEMS = 'SET_REPETITIONS_LIST_ITEMS';
export const SET_REPETITIONS_LIST_IS_LOADING = 'SET_REPETITIONS_LIST_IS_LOADING';
export const SET_REPETITIONS_LIST_META = 'SET_REPETITIONS_LIST_META'
export const SET_REPETITIONS_LIST_LINKS = 'SET_REPETITIONS_LIST_LINKS'
export const SET_REPETITIONS_LIST_MESSAGE = 'SET_REPETITIONS_LIST_MESSAGE'
export const SET_REPETITIONS_LIST_SEARCH_ITEMS = 'SET_REPETITIONS_LIST_SEARCH_ITEMS'
export const SET_REPETITIONS_LIST_RESET = 'SET_REPETITIONS_LIST_RESET'    