export const SET_BOOKS_CREATE_IS_LOADING = 'SET_BOOKS_CREATE_IS_LOADING';
export const SET_BOOKS_CREATE_IS_CREATE = 'SET_BOOKS_CREATE_IS_CREATE'
export const SET_BOOKS_CREATE_ITEM= 'SET_BOOKS_CREATE_ITEM'
export const SET_BOOKS_CREATE_MESSAGE = 'SET_BOOKS_CREATE_MESSAGE'
export const SET_BOOKS_CREATE_RESET = 'SET_BOOKS_CREATE_RESET'
