export const SET_EXERCICES_LIST_ITEMS = 'SET_EXERCICES_LIST_ITEMS';
export const SET_EXERCICES_LIST_IS_LOADING = 'SET_EXERCICES_LIST_IS_LOADING';
export const SET_EXERCICES_LIST_META = 'SET_EXERCICES_LIST_META'
export const SET_EXERCICES_LIST_LINKS = 'SET_EXERCICES_LIST_LINKS'
export const SET_EXERCICES_LIST_MESSAGE = 'SET_EXERCICES_LIST_MESSAGE'
export const SET_EXERCICES_LIST_SEARCH_ITEMS = 'SET_EXERCICES_LIST_SEARCH_ITEMS'
export const SET_EXERCICES_LIST_RESET = 'SET_EXERCICES_LIST_RESET'    