export const SET_COURS_CREATE_IS_LOADING = 'SET_COURS_CREATE_IS_LOADING';
export const SET_COURS_CREATE_IS_CREATE = 'SET_COURS_CREATE_IS_CREATE'
export const SET_COURS_CREATE_ITEM= 'SET_COURS_CREATE_ITEM'
export const SET_COURS_CREATE_MESSAGE = 'SET_COURS_CREATE_MESSAGE'
export const SET_COURS_CREATE_RESET = 'SET_COURS_CREATE_RESET'
