export const SET_BOOKS_LIST_ITEMS = 'SET_BOOKS_LIST_ITEMS';
export const SET_BOOKS_LIST_IS_LOADING = 'SET_BOOKS_LIST_IS_LOADING';
export const SET_BOOKS_LIST_META = 'SET_BOOKS_LIST_META'
export const SET_BOOKS_LIST_LINKS = 'SET_BOOKS_LIST_LINKS'
export const SET_BOOKS_LIST_MESSAGE = 'SET_BOOKS_LIST_MESSAGE'
export const SET_BOOKS_LIST_SEARCH_ITEMS = 'SET_BOOKS_LIST_SEARCH_ITEMS'
export const SET_BOOKS_LIST_RESET = 'SET_BOOKS_LIST_RESET'    