export const SET_SOUSTITRES_DELETE_IS_LOADING = 'SET_SOUSTITRES_DELETE_IS_LOADING';
export const SET_SOUSTITRES_DELETE_IS_DELETE = 'SET_SOUSTITRES_DELETE_IS_DELETE'
export const SET_SOUSTITRES_DELETE_ITEM= 'SET_SOUSTITRES_DELETE_ITEM'
export const SET_SOUSTITRES_DELETE_MESSAGE = 'SET_SOUSTITRES_DELETE_MESSAGE'
export const SET_SOUSTITRES_DELETE_RESET = 'SET_SOUSTITRES_DELETE_RESET'
