export const SET_COURS_DELETE_IS_LOADING = 'SET_COURS_DELETE_IS_LOADING';
export const SET_COURS_DELETE_IS_DELETE = 'SET_COURS_DELETE_IS_DELETE'
export const SET_COURS_DELETE_ITEM= 'SET_COURS_DELETE_ITEM'
export const SET_COURS_DELETE_MESSAGE = 'SET_COURS_DELETE_MESSAGE'
export const SET_COURS_DELETE_RESET = 'SET_COURS_DELETE_RESET'
