export const SET_SOUSTITRES_LIST_ITEMS = 'SET_SOUSTITRES_LIST_ITEMS';
export const SET_SOUSTITRES_LIST_IS_LOADING = 'SET_SOUSTITRES_LIST_IS_LOADING';
export const SET_SOUSTITRES_LIST_META = 'SET_SOUSTITRES_LIST_META'
export const SET_SOUSTITRES_LIST_LINKS = 'SET_SOUSTITRES_LIST_LINKS'
export const SET_SOUSTITRES_LIST_MESSAGE = 'SET_SOUSTITRES_LIST_MESSAGE'
export const SET_SOUSTITRES_LIST_SEARCH_ITEMS = 'SET_SOUSTITRES_LIST_SEARCH_ITEMS'
export const SET_SOUSTITRES_LIST_RESET = 'SET_SOUSTITRES_LIST_RESET'    