export const SET_REPETITIONS_DELETE_IS_LOADING = 'SET_REPETITIONS_DELETE_IS_LOADING';
export const SET_REPETITIONS_DELETE_IS_DELETE = 'SET_REPETITIONS_DELETE_IS_DELETE'
export const SET_REPETITIONS_DELETE_ITEM= 'SET_REPETITIONS_DELETE_ITEM'
export const SET_REPETITIONS_DELETE_MESSAGE = 'SET_REPETITIONS_DELETE_MESSAGE'
export const SET_REPETITIONS_DELETE_RESET = 'SET_REPETITIONS_DELETE_RESET'
