export const SET_USER_REPETS_LIST_ITEMS = 'SET_USER_REPETS_LIST_ITEMS';
export const SET_USER_REPETS_LIST_IS_LOADING = 'SET_USER_REPETS_LIST_IS_LOADING';
export const SET_USER_REPETS_LIST_META = 'SET_USER_REPETS_LIST_META'
export const SET_USER_REPETS_LIST_LINKS = 'SET_USER_REPETS_LIST_LINKS'
export const SET_USER_REPETS_LIST_MESSAGE = 'SET_USER_REPETS_LIST_MESSAGE'
export const SET_USER_REPETS_LIST_SEARCH_ITEMS = 'SET_USER_REPETS_LIST_SEARCH_ITEMS'
export const SET_USER_REPETS_LIST_RESET = 'SET_USER_REPETS_LIST_RESET'    