export const SET_BOOKTYPES_CREATE_IS_LOADING = 'SET_BOOKTYPES_CREATE_IS_LOADING';
export const SET_BOOKTYPES_CREATE_IS_CREATE = 'SET_BOOKTYPES_CREATE_IS_CREATE'
export const SET_BOOKTYPES_CREATE_ITEM= 'SET_BOOKTYPES_CREATE_ITEM'
export const SET_BOOKTYPES_CREATE_MESSAGE = 'SET_BOOKTYPES_CREATE_MESSAGE'
export const SET_BOOKTYPES_CREATE_RESET = 'SET_BOOKTYPES_CREATE_RESET'
