export const SET_BOOKS_UPDATE_IS_LOADING = 'SET_BOOKS_UPDATE_IS_LOADING';
export const SET_BOOKS_UPDATE_IS_UPDATE = 'SET_BOOKS_UPDATE_IS_UPDATE'
export const SET_BOOKS_UPDATE_ITEM= 'SET_BOOKS_UPDATE_ITEM'
export const SET_BOOKS_UPDATE_MESSAGE = 'SET_BOOKS_UPDATE_MESSAGE'
export const SET_BOOKS_UPDATE_RESET = 'SET_BOOKS_UPDATE_RESET'
