export const SET_BOOKFAVS_UPDATE_IS_LOADING = 'SET_BOOKFAVS_UPDATE_IS_LOADING';
export const SET_BOOKFAVS_UPDATE_IS_UPDATE = 'SET_BOOKFAVS_UPDATE_IS_UPDATE'
export const SET_BOOKFAVS_UPDATE_ITEM= 'SET_BOOKFAVS_UPDATE_ITEM'
export const SET_BOOKFAVS_UPDATE_MESSAGE = 'SET_BOOKFAVS_UPDATE_MESSAGE'
export const SET_BOOKFAVS_UPDATE_RESET = 'SET_BOOKFAVS_UPDATE_RESET'
