export const SET_EXERCICES_DELETE_IS_LOADING = 'SET_EXERCICES_DELETE_IS_LOADING';
export const SET_EXERCICES_DELETE_IS_DELETE = 'SET_EXERCICES_DELETE_IS_DELETE'
export const SET_EXERCICES_DELETE_ITEM= 'SET_EXERCICES_DELETE_ITEM'
export const SET_EXERCICES_DELETE_MESSAGE = 'SET_EXERCICES_DELETE_MESSAGE'
export const SET_EXERCICES_DELETE_RESET = 'SET_EXERCICES_DELETE_RESET'
