export const SET_SOUSTITRES_CREATE_IS_LOADING = 'SET_SOUSTITRES_CREATE_IS_LOADING';
export const SET_SOUSTITRES_CREATE_IS_CREATE = 'SET_SOUSTITRES_CREATE_IS_CREATE'
export const SET_SOUSTITRES_CREATE_ITEM= 'SET_SOUSTITRES_CREATE_ITEM'
export const SET_SOUSTITRES_CREATE_MESSAGE = 'SET_SOUSTITRES_CREATE_MESSAGE'
export const SET_SOUSTITRES_CREATE_RESET = 'SET_SOUSTITRES_CREATE_RESET'
