export const SET_BOOKTYPES_LIST_ITEMS = 'SET_BOOKTYPES_LIST_ITEMS';
export const SET_BOOKTYPES_LIST_IS_LOADING = 'SET_BOOKTYPES_LIST_IS_LOADING';
export const SET_BOOKTYPES_LIST_META = 'SET_BOOKTYPES_LIST_META'
export const SET_BOOKTYPES_LIST_LINKS = 'SET_BOOKTYPES_LIST_LINKS'
export const SET_BOOKTYPES_LIST_MESSAGE = 'SET_BOOKTYPES_LIST_MESSAGE'
export const SET_BOOKTYPES_LIST_SEARCH_ITEMS = 'SET_BOOKTYPES_LIST_SEARCH_ITEMS'
export const SET_BOOKTYPES_LIST_RESET = 'SET_BOOKTYPES_LIST_RESET'    