export const SET_BOOKTYPES_DELETE_IS_LOADING = 'SET_BOOKTYPES_DELETE_IS_LOADING';
export const SET_BOOKTYPES_DELETE_IS_DELETE = 'SET_BOOKTYPES_DELETE_IS_DELETE'
export const SET_BOOKTYPES_DELETE_ITEM= 'SET_BOOKTYPES_DELETE_ITEM'
export const SET_BOOKTYPES_DELETE_MESSAGE = 'SET_BOOKTYPES_DELETE_MESSAGE'
export const SET_BOOKTYPES_DELETE_RESET = 'SET_BOOKTYPES_DELETE_RESET'
