export const SET_BOOKTYPES_UPDATE_IS_LOADING = 'SET_BOOKTYPES_UPDATE_IS_LOADING';
export const SET_BOOKTYPES_UPDATE_IS_UPDATE = 'SET_BOOKTYPES_UPDATE_IS_UPDATE'
export const SET_BOOKTYPES_UPDATE_ITEM= 'SET_BOOKTYPES_UPDATE_ITEM'
export const SET_BOOKTYPES_UPDATE_MESSAGE = 'SET_BOOKTYPES_UPDATE_MESSAGE'
export const SET_BOOKTYPES_UPDATE_RESET = 'SET_BOOKTYPES_UPDATE_RESET'
