export const SET_USER_REPETS_UPDATE_IS_LOADING = 'SET_USER_REPETS_UPDATE_IS_LOADING';
export const SET_USER_REPETS_UPDATE_IS_UPDATE = 'SET_USER_REPETS_UPDATE_IS_UPDATE'
export const SET_USER_REPETS_UPDATE_ITEM= 'SET_USER_REPETS_UPDATE_ITEM'
export const SET_USER_REPETS_UPDATE_MESSAGE = 'SET_USER_REPETS_UPDATE_MESSAGE'
export const SET_USER_REPETS_UPDATE_RESET = 'SET_USER_REPETS_UPDATE_RESET'
