export const SET_QUIZS_DELETE_IS_LOADING = 'SET_QUIZS_DELETE_IS_LOADING';
export const SET_QUIZS_DELETE_IS_DELETE = 'SET_QUIZS_DELETE_IS_DELETE'
export const SET_QUIZS_DELETE_ITEM= 'SET_QUIZS_DELETE_ITEM'
export const SET_QUIZS_DELETE_MESSAGE = 'SET_QUIZS_DELETE_MESSAGE'
export const SET_QUIZS_DELETE_RESET = 'SET_QUIZS_DELETE_RESET'
