export const SET_USERS_CREATE_IS_LOADING = 'SET_USERS_CREATE_IS_LOADING';
export const SET_USERS_CREATE_IS_CREATE = 'SET_USERS_CREATE_IS_CREATE'
export const SET_USERS_CREATE_ITEM= 'SET_USERS_CREATE_ITEM'
export const SET_USERS_CREATE_MESSAGE = 'SET_USERS_CREATE_MESSAGE'
export const SET_USERS_CREATE_RESET = 'SET_USERS_CREATE_RESET'
