export const SET_CLASSROOMS_LIST_ITEMS = 'SET_CLASSROOMS_LIST_ITEMS';
export const SET_CLASSROOMS_LIST_IS_LOADING = 'SET_CLASSROOMS_LIST_IS_LOADING';
export const SET_CLASSROOMS_LIST_META = 'SET_CLASSROOMS_LIST_META'
export const SET_CLASSROOMS_LIST_LINKS = 'SET_CLASSROOMS_LIST_LINKS'
export const SET_CLASSROOMS_LIST_MESSAGE = 'SET_CLASSROOMS_LIST_MESSAGE'
export const SET_CLASSROOMS_LIST_SEARCH_ITEMS = 'SET_CLASSROOMS_LIST_SEARCH_ITEMS'
export const SET_CLASSROOMS_LIST_RESET = 'SET_CLASSROOMS_LIST_RESET'    