export const SET_SUBJECTS_UPDATE_IS_LOADING = 'SET_SUBJECTS_UPDATE_IS_LOADING';
export const SET_SUBJECTS_UPDATE_IS_UPDATE = 'SET_SUBJECTS_UPDATE_IS_UPDATE'
export const SET_SUBJECTS_UPDATE_ITEM= 'SET_SUBJECTS_UPDATE_ITEM'
export const SET_SUBJECTS_UPDATE_MESSAGE = 'SET_SUBJECTS_UPDATE_MESSAGE'
export const SET_SUBJECTS_UPDATE_RESET = 'SET_SUBJECTS_UPDATE_RESET'
