export const SET_EXERCICES_CREATE_IS_LOADING = 'SET_EXERCICES_CREATE_IS_LOADING';
export const SET_EXERCICES_CREATE_IS_CREATE = 'SET_EXERCICES_CREATE_IS_CREATE'
export const SET_EXERCICES_CREATE_ITEM= 'SET_EXERCICES_CREATE_ITEM'
export const SET_EXERCICES_CREATE_MESSAGE = 'SET_EXERCICES_CREATE_MESSAGE'
export const SET_EXERCICES_CREATE_RESET = 'SET_EXERCICES_CREATE_RESET'
