export const SET_SUBJECTS_LIST_ITEMS = 'SET_SUBJECTS_LIST_ITEMS';
export const SET_SUBJECTS_LIST_IS_LOADING = 'SET_SUBJECTS_LIST_IS_LOADING';
export const SET_SUBJECTS_LIST_META = 'SET_SUBJECTS_LIST_META'
export const SET_SUBJECTS_LIST_LINKS = 'SET_SUBJECTS_LIST_LINKS'
export const SET_SUBJECTS_LIST_MESSAGE = 'SET_SUBJECTS_LIST_MESSAGE'
export const SET_SUBJECTS_LIST_RESET = 'SET_SUBJECTS_LIST_RESET'    