export const SET_USERS_LIST_ITEMS = 'SET_USERS_LIST_ITEMS';
export const SET_USERS_LIST_IS_LOADING = 'SET_USERS_LIST_IS_LOADING';
export const SET_USERS_LIST_META = 'SET_USERS_LIST_META'
export const SET_USERS_LIST_LINKS = 'SET_USERS_LIST_LINKS'
export const SET_USERS_LIST_MESSAGE = 'SET_USERS_LIST_MESSAGE'
export const SET_USERS_LIST_RESET = 'SET_USERS_LIST_RESET'    