export const SET_QUIZS_LIST_ITEMS = 'SET_QUIZS_LIST_ITEMS';
export const SET_QUIZS_LIST_IS_LOADING = 'SET_QUIZS_LIST_IS_LOADING';
export const SET_QUIZS_LIST_META = 'SET_QUIZS_LIST_META'
export const SET_QUIZS_LIST_LINKS = 'SET_QUIZS_LIST_LINKS'
export const SET_QUIZS_LIST_MESSAGE = 'SET_QUIZS_LIST_MESSAGE'
export const SET_QUIZS_LIST_SEARCH_ITEMS = 'SET_QUIZS_LIST_SEARCH_ITEMS'
export const SET_QUIZS_LIST_RESET = 'SET_QUIZS_LIST_RESET'    