export const SET_COURS_LIST_ITEMS = 'SET_COURS_LIST_ITEMS';
export const SET_COURS_LIST_IS_LOADING = 'SET_COURS_LIST_IS_LOADING';
export const SET_COURS_LIST_META = 'SET_COURS_LIST_META'
export const SET_COURS_LIST_LINKS = 'SET_COURS_LIST_LINKS'
export const SET_COURS_LIST_MESSAGE = 'SET_COURS_LIST_MESSAGE'
export const SET_COURS_LIST_SEARCH_ITEMS = 'SET_COURS_LIST_SEARCH_ITEMS'
export const SET_COURS_LIST_RESET = 'SET_COURS_LIST_RESET'    