export const SET_USERS_DELETE_IS_LOADING = 'SET_USERS_DELETE_IS_LOADING';
export const SET_USERS_DELETE_IS_DELETE = 'SET_USERS_DELETE_IS_DELETE'
export const SET_USERS_DELETE_ITEM= 'SET_USERS_DELETE_ITEM'
export const SET_USERS_DELETE_MESSAGE = 'SET_USERS_DELETE_MESSAGE'
export const SET_USERS_DELETE_RESET = 'SET_USERS_DELETE_RESET'
