export const SET_SOUSTITRES_UPDATE_IS_LOADING = 'SET_SOUSTITRES_UPDATE_IS_LOADING';
export const SET_SOUSTITRES_UPDATE_IS_UPDATE = 'SET_SOUSTITRES_UPDATE_IS_UPDATE'
export const SET_SOUSTITRES_UPDATE_ITEM= 'SET_SOUSTITRES_UPDATE_ITEM'
export const SET_SOUSTITRES_UPDATE_MESSAGE = 'SET_SOUSTITRES_UPDATE_MESSAGE'
export const SET_SOUSTITRES_UPDATE_RESET = 'SET_SOUSTITRES_UPDATE_RESET'
